### ISSUE TITLE
Connector doesn't crash/exit when mongodb authentication fails

### ISSUE THREAD

**Issue by nivemaham** [RADAR-CNS/RADAR-MongoDbConnector#12]
Connector instance keeps running even If the authentication of mongodb fails. Then keeps reporting 0 records have been processed.
The connector should exit the process with proper error code, to inform the status of the connector instance properly.

```
[radar-mongodb-connector_1  | 	at com.mongodb.connection.BaseCluster.createTimeoutException(BaseCluster.java:375)
radar-mongodb-connector_1  | 	at com.mongodb.connection.BaseCluster.selectServer(BaseCluster.java:104)
radar-mongodb-connector_1  | 	at com.mongodb.binding.ClusterBinding$ClusterBindingConnectionSource.<init>(ClusterBinding.java:75)
radar-mongodb-connector_1  | 	at com.mongodb.binding.ClusterBinding$ClusterBindingConnectionSource.<init>(ClusterBinding.java:71)
radar-mongodb-connector_1  | 	at com.mongodb.binding.ClusterBinding.getReadConnectionSource(ClusterBinding.java:63)
radar-mongodb-connector_1  | 	at com.mongodb.operation.CommandOperationHelper.executeWrappedCommandProtocol(CommandOperationHelper.java:90)
radar-mongodb-connector_1  | 	at com.mongodb.operation.CommandOperationHelper.executeWrappedCommandProtocol(CommandOperationHelper.java:85)
radar-mongodb-connector_1  | 	at com.mongodb.operation.CommandReadOperation.execute(CommandReadOperation.java:55)
radar-mongodb-connector_1  | 	at com.mongodb.Mongo.execute(Mongo.java:818)
radar-mongodb-connector_1  | 	at com.mongodb.Mongo$2.execute(Mongo.java:805)
radar-mongodb-connector_1  | 	at com.mongodb.MongoDatabaseImpl.runCommand(MongoDatabaseImpl.java:130)
radar-mongodb-connector_1  | 	at com.mongodb.MongoDatabaseImpl.runCommand(MongoDatabaseImpl.java:124)
radar-mongodb-connector_1  | 	at com.mongodb.MongoDatabaseImpl.runCommand(MongoDatabaseImpl.java:114)
radar-mongodb-connector_1  | 	at org.radarcns.mongodb.MongoWrapper.checkConnection(MongoWrapper.java:106)
radar-mongodb-connector_1  | 	at org.radarcns.mongodb.MongoDbWriter.<init>(MongoDbWriter.java:83)
radar-mongodb-connector_1  | 	at org.radarcns.mongodb.MongoDbSinkTask.createMongoDbWriter(MongoDbSinkTask.java:98)
radar-mongodb-connector_1  | 	at org.radarcns.mongodb.MongoDbSinkTask.start(MongoDbSinkTask.java:87)
radar-mongodb-connector_1  | 	at org.apache.kafka.connect.runtime.WorkerSinkTask.initializeAndStart(WorkerSinkTask.java:221)
radar-mongodb-connector_1  | 	at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:140)
radar-mongodb-connector_1  | 	at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:140)
radar-mongodb-connector_1  | 	at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:175)
radar-mongodb-connector_1  | 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
radar-mongodb-connector_1  | 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
radar-mongodb-connector_1  | 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
radar-mongodb-connector_1  | 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
radar-mongodb-connector_1  | 	at java.lang.Thread.run(Thread.java:745)
radar-mongodb-connector_1  | [2017-03-13 16:25:16,471] INFO MongoDB connection is has been closed (org.radarcns.mongodb.MongoWrapper)
radar-mongodb-connector_1  | [2017-03-13 16:25:16,471] ERROR Task radar-connector-mongodb-sink-0 threw an uncaught and unrecoverable exception (org.apache.kafka.connect.runtime.WorkerTask)
radar-mongodb-connector_1  | org.apache.kafka.connect.errors.ConnectException: Cannot connect to MongoDB database
radar-mongodb-connector_1  | 	at org.radarcns.mongodb.MongoDbWriter.<init>(MongoDbWriter.java:85)
radar-mongodb-connector_1  | 	at org.radarcns.mongodb.MongoDbSinkTask.createMongoDbWriter(MongoDbSinkTask.java:98)
radar-mongodb-connector_1  | 	at org.radarcns.mongodb.MongoDbSinkTask.start(MongoDbSinkTask.java:87)
radar-mongodb-connector_1  | 	at org.apache.kafka.connect.runtime.WorkerSinkTask.initializeAndStart(WorkerSinkTask.java:221)
radar-mongodb-connector_1  | 	at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:140)
radar-mongodb-connector_1  | 	at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:140)
radar-mongodb-connector_1  | 	at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:175)
radar-mongodb-connector_1  | 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
radar-mongodb-connector_1  | 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
radar-mongodb-connector_1  | 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
radar-mongodb-connector_1  | 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
radar-mongodb-connector_1  | 	at java.lang.Thread.run(Thread.java:745)
radar-mongodb-connector_1  | [2017-03-13 16:25:16,473] ERROR Task is being killed and will not recover until manually restarted (org.apache.kafka.connect.runtime.WorkerTask)
radar-mongodb-connector_1  | [2017-03-13 16:25:16,473] ERROR Task radar-connector-mongodb-sink-0 threw an uncaught and unrecoverable exception during shutdown (org.apache.kafka.connect.runtime.WorkerTask)
radar-mongodb-connector_1  | java.lang.NullPointerException
radar-mongodb-connector_1  | 	at org.radarcns.mongodb.MongoDbSinkTask.stop(MongoDbSinkTask.java:145)
radar-mongodb-connector_1  | 	at org.apache.kafka.connect.runtime.WorkerSinkTask.close(WorkerSinkTask.java:127)
radar-mongodb-connector_1  | 	at org.apache.kafka.connect.runtime.WorkerTask.doClose(WorkerTask.java:121)
radar-mongodb-connector_1  | 	at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:146)
radar-mongodb-connector_1  | 	at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:175)
radar-mongodb-connector_1  | 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
radar-mongodb-connector_1  | 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
radar-mongodb-connector_1  | 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
radar-mongodb-connector_1  | 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
radar-mongodb-connector_1  | 	at java.lang.Thread.run(Thread.java:745)
```

**Comment by nivemaham** [comment]
@blootsvoets What is your opinion about this?

**Comment by blootsvoets** [comment]
Should fix, are you up for it? Possibly by fixing the last `nullpointerexception` we see above? I'm not sure what the default behaviour should be: should connectors keep retrying or fail fast?

**Comment by nivemaham** [comment]
I would recommend fail fast IMO.
The above scenario was when the credentials were given wrong.
In that case, the connector should check for connection and when the connection fails, the SinkTask also should fail fast. yes. I am looking into it. Would be better if we fix this before the release.

**Comment by nivemaham** [comment]
@blootsvoets the solution i could find was only to allow the runtime exceptions  and close the initialized resources. Further we can also add a validation to process SinkRecords only if there is a writer initialized.
The current solution is commit on this [revision](https://github.com/RADAR-CNS/MongoDb-Sink-Connector/commit/6852b2864fb2a03ac5c1181e240702af38acdd59).
However, stopping the connector is not really feasible from available APIs.

Current logging would look like,
```
radar-mongodb-connector_1  | 	ssl.truststore.password = null
radar-mongodb-connector_1  | 	ssl.truststore.type = JKS
radar-mongodb-connector_1  | 	value.deserializer = class org.apache.kafka.common.serialization.ByteArrayDeserializer
radar-mongodb-connector_1  |  (org.apache.kafka.clients.consumer.ConsumerConfig)
radar-mongodb-connector_1  | [2017-04-13 15:25:07,177] INFO Kafka version : 0.10.1.1 (org.apache.kafka.common.utils.AppInfoParser)
radar-mongodb-connector_1  | [2017-04-13 15:25:07,177] INFO Kafka commitId : f10ef2720b03b247 (org.apache.kafka.common.utils.AppInfoParser)
radar-mongodb-connector_1  | [2017-04-13 15:25:07,184] INFO Created connector radar-connector-mongodb-sink (org.apache.kafka.connect.cli.ConnectStandalone)
radar-mongodb-connector_1  | [2017-04-13 15:25:07,185] INFO 0 have been processed (org.radarcns.mongodb.MongoDbSinkTask)
radar-mongodb-connector_1  | [2017-04-13 15:25:07,456] INFO Cluster created with settings {hosts=[hotstorage:27017], mode=SINGLE, requiredClusterType=UNKNOWN, serverSelectionTimeout='30000 ms', maxWaitQueueSize=500} (org.mongodb.driver.cluster)
radar-mongodb-connector_1  | [2017-04-13 15:25:07,608] INFO 0 have been written in MongoDB 0 records need to be processed. (org.radarcns.mongodb.MongoDbWriter)
radar-mongodb-connector_1  | [2017-04-13 15:25:07,657] INFO No server chosen by ReadPreferenceServerSelector{readPreference=primary} from cluster description ClusterDescription{type=UNKNOWN, connectionMode=SINGLE, serverDescriptions=[ServerDescription{address=hotstorage:27017, type=UNKNOWN, state=CONNECTING}]}. Waiting for 30000 ms before timing out (org.mongodb.driver.cluster)
radar-mongodb-connector_1  | [2017-04-13 15:25:08,080] INFO Exception in monitor thread while connecting to server hotstorage:27017 (org.mongodb.driver.cluster)
radar-mongodb-connector_1  | com.mongodb.MongoSecurityException: Exception authenticating MongoCredential{mechanism=null, userName='restapi', source='hotstorage', password=<hidden>, mechanismProperties={}}
radar-mongodb-connector_1  | 	at com.mongodb.connection.SaslAuthenticator.wrapInMongoSecurityException(SaslAuthenticator.java:157)
radar-mongodb-connector_1  | 	at com.mongodb.connection.SaslAuthenticator.access$200(SaslAuthenticator.java:37)
radar-mongodb-connector_1  | 	at com.mongodb.connection.SaslAuthenticator$1.run(SaslAuthenticator.java:66)
radar-mongodb-connector_1  | 	at com.mongodb.connection.SaslAuthenticator$1.run(SaslAuthenticator.java:44)
radar-mongodb-connector_1  | 	at com.mongodb.connection.SaslAuthenticator.doAsSubject(SaslAuthenticator.java:162)
radar-mongodb-connector_1  | 	at com.mongodb.connection.SaslAuthenticator.authenticate(SaslAuthenticator.java:44)
radar-mongodb-connector_1  | 	at com.mongodb.connection.DefaultAuthenticator.authenticate(DefaultAuthenticator.java:32)
radar-mongodb-connector_1  | 	at com.mongodb.connection.InternalStreamConnectionInitializer.authenticateAll(InternalStreamConnectionInitializer.java:99)
radar-mongodb-connector_1  | 	at com.mongodb.connection.InternalStreamConnectionInitializer.initialize(InternalStreamConnectionInitializer.java:44)
radar-mongodb-connector_1  | 	at com.mongodb.connection.InternalStreamConnection.open(InternalStreamConnection.java:116)
radar-mongodb-connector_1  | 	at com.mongodb.connection.DefaultServerMonitor$ServerMonitorRunnable.run(DefaultServerMonitor.java:116)
radar-mongodb-connector_1  | 	at java.lang.Thread.run(Thread.java:745)
radar-mongodb-connector_1  | Caused by: com.mongodb.MongoCommandException: Command failed with error 18: 'Authentication failed.' on server hotstorage:27017. The full response is { "ok" : 0.0, "code" : 18, "errmsg" : "Authentication failed." }
radar-mongodb-connector_1  | 	at com.mongodb.connection.CommandHelper.createCommandFailureException(CommandHelper.java:170)
radar-mongodb-connector_1  | 	at com.mongodb.connection.CommandHelper.receiveCommandResult(CommandHelper.java:123)
radar-mongodb-connector_1  | 	at com.mongodb.connection.CommandHelper.executeCommand(CommandHelper.java:32)
radar-mongodb-connector_1  | 	at com.mongodb.connection.SaslAuthenticator.sendSaslContinue(SaslAuthenticator.java:121)
radar-mongodb-connector_1  | 	at com.mongodb.connection.SaslAuthenticator.access$100(SaslAuthenticator.java:37)
radar-mongodb-connector_1  | 	at com.mongodb.connection.SaslAuthenticator$1.run(SaslAuthenticator.java:63)
radar-mongodb-connector_1  | 	... 9 more
radar-mongodb-connector_1  | [2017-04-13 15:25:16,285] INFO Reflections took 12214 ms to scan 265 urls, producing 13143 keys and 86610 values  (org.reflections.Reflections)
radar-mongodb-connector_1  | [2017-04-13 15:25:37,185] INFO 0 have been processed (org.radarcns.mongodb.MongoDbSinkTask)
radar-mongodb-connector_1  | [2017-04-13 15:25:37,608] INFO 0 have been written in MongoDB 0 records need to be processed. (org.radarcns.mongodb.MongoDbWriter)
radar-mongodb-connector_1  | [2017-04-13 15:25:37,659] ERROR Error during MongoDB connection test (org.radarcns.mongodb.MongoWrapper)
radar-mongodb-connector_1  | com.mongodb.MongoTimeoutException: Timed out after 30000 ms while waiting for a server that matches ReadPreferenceServerSelector{readPreference=primary}. Client view of cluster state is {type=UNKNOWN, servers=[{address=hotstorage:27017, type=UNKNOWN, state=CONNECTING, exception={com.mongodb.MongoSecurityException: Exception authenticating MongoCredential{mechanism=null, userName='restapi', source='hotstorage', password=<hidden>, mechanismProperties={}}}, caused by {com.mongodb.MongoCommandException: Command failed with error 18: 'Authentication failed.' on server hotstorage:27017. The full response is { "ok" : 0.0, "code" : 18, "errmsg" : "Authentication failed." }}}]
radar-mongodb-connector_1  | 	at com.mongodb.connection.BaseCluster.createTimeoutException(BaseCluster.java:375)
radar-mongodb-connector_1  | 	at com.mongodb.connection.BaseCluster.selectServer(BaseCluster.java:104)
radar-mongodb-connector_1  | 	at com.mongodb.binding.ClusterBinding$ClusterBindingConnectionSource.<init>(ClusterBinding.java:75)
radar-mongodb-connector_1  | 	at com.mongodb.binding.ClusterBinding$ClusterBindingConnectionSource.<init>(ClusterBinding.java:71)
radar-mongodb-connector_1  | 	at com.mongodb.binding.ClusterBinding.getReadConnectionSource(ClusterBinding.java:63)
radar-mongodb-connector_1  | 	at com.mongodb.operation.CommandOperationHelper.executeWrappedCommandProtocol(CommandOperationHelper.java:90)
radar-mongodb-connector_1  | 	at com.mongodb.operation.CommandOperationHelper.executeWrappedCommandProtocol(CommandOperationHelper.java:85)
radar-mongodb-connector_1  | 	at com.mongodb.operation.CommandReadOperation.execute(CommandReadOperation.java:55)
radar-mongodb-connector_1  | 	at com.mongodb.Mongo.execute(Mongo.java:818)
radar-mongodb-connector_1  | 	at com.mongodb.Mongo$2.execute(Mongo.java:805)
radar-mongodb-connector_1  | 	at com.mongodb.MongoDatabaseImpl.runCommand(MongoDatabaseImpl.java:130)
radar-mongodb-connector_1  | 	at com.mongodb.MongoDatabaseImpl.runCommand(MongoDatabaseImpl.java:124)
radar-mongodb-connector_1  | 	at com.mongodb.MongoDatabaseImpl.runCommand(MongoDatabaseImpl.java:114)
radar-mongodb-connector_1  | 	at org.radarcns.mongodb.MongoWrapper.checkConnection(MongoWrapper.java:106)
radar-mongodb-connector_1  | 	at org.radarcns.mongodb.MongoDbWriter.<init>(MongoDbWriter.java:83)
radar-mongodb-connector_1  | 	at org.radarcns.mongodb.MongoDbSinkTask.createMongoDbWriter(MongoDbSinkTask.java:108)
radar-mongodb-connector_1  | 	at org.radarcns.mongodb.MongoDbSinkTask.start(MongoDbSinkTask.java:88)
radar-mongodb-connector_1  | 	at org.apache.kafka.connect.runtime.WorkerSinkTask.initializeAndStart(WorkerSinkTask.java:221)
radar-mongodb-connector_1  | 	at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:140)
radar-mongodb-connector_1  | 	at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:140)
radar-mongodb-connector_1  | 	at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:175)
radar-mongodb-connector_1  | 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
radar-mongodb-connector_1  | 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
radar-mongodb-connector_1  | 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
radar-mongodb-connector_1  | 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
radar-mongodb-connector_1  | 	at java.lang.Thread.run(Thread.java:745)
radar-mongodb-connector_1  | [2017-04-13 15:25:37,665] INFO MongoDB connection is has been closed (org.radarcns.mongodb.MongoWrapper)
radar-mongodb-connector_1  | [2017-04-13 15:25:37,666] ERROR Task radar-connector-mongodb-sink-0 threw an uncaught and unrecoverable exception (org.apache.kafka.connect.runtime.WorkerTask)
radar-mongodb-connector_1  | org.apache.kafka.connect.errors.ConnectException: Cannot connect to MongoDB database
radar-mongodb-connector_1  | 	at org.radarcns.mongodb.MongoDbWriter.<init>(MongoDbWriter.java:85)
radar-mongodb-connector_1  | 	at org.radarcns.mongodb.MongoDbSinkTask.createMongoDbWriter(MongoDbSinkTask.java:108)
radar-mongodb-connector_1  | 	at org.radarcns.mongodb.MongoDbSinkTask.start(MongoDbSinkTask.java:88)
radar-mongodb-connector_1  | 	at org.apache.kafka.connect.runtime.WorkerSinkTask.initializeAndStart(WorkerSinkTask.java:221)
radar-mongodb-connector_1  | 	at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:140)
radar-mongodb-connector_1  | 	at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:140)
radar-mongodb-connector_1  | 	at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:175)
radar-mongodb-connector_1  | 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
radar-mongodb-connector_1  | 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
radar-mongodb-connector_1  | 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
radar-mongodb-connector_1  | 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
radar-mongodb-connector_1  | 	at java.lang.Thread.run(Thread.java:745)
radar-mongodb-connector_1  | [2017-04-13 15:25:37,666] ERROR Task is being killed and will not recover until manually restarted (org.apache.kafka.connect.runtime.WorkerTask)
radar-mongodb-connector_1  | [2017-04-13 15:25:37,667] INFO Stopping MongoDBSinkTask (org.radarcns.mongodb.MongoDbSinkTask)
radar-mongodb-connector_1  | [2017-04-13 15:25:37,667] INFO Stoped MongoDBSinkTask (org.radarcns.mongodb.MongoDbSinkTask)
```

**Comment by nivemaham** [comment]
Fixed by this [revision](https://github.com/RADAR-CNS/MongoDb-Sink-Connector/pull/14/commits/6852b2864fb2a03ac5c1181e240702af38acdd59)
