### ISSUE TITLE
Am I missing a dependency - NoClassDefFoundError

### ISSUE THREAD

**Issue by psmod2** [RADAR-CNS/RADAR-MongoDbConnector#30]
Hi,

I've installed the connector all ok and it loads fine. However when I go to actually start it with some basic configuration:

```
  "connector.class": "org.radarcns.connect.mongodb.MongoDbSinkConnector",
  "mongo.database": "sinktest",
  "mongo.host": "localhost",
  "topics": "bxB",
  "tasks.max": "1",
  "name": "MongoDbSinkConnector"
```

I get the following error:

```
java.lang.NoClassDefFoundError: com/mongodb/MongoException
	at org.radarcns.connect.mongodb.MongoDbSinkTask.createMongoDbWriter(MongoDbSinkTask.java:106)
	at org.radarcns.connect.mongodb.MongoDbSinkTask.start(MongoDbSinkTask.java:88)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.initializeAndStart(WorkerSinkTask.java:267)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:163)
	at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:170)
	at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:214)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.ClassNotFoundException: com.mongodb.MongoException
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 11 more
```

Any ideas what I'm missing / how to resolve this?

Thanks.

**Comment by blootsvoets** [comment]
Yes, I'll update the README about that. The docker file does all the necessary steps:
```shell
# depending on your installation, change this path
CONNECT_PLUGIN_PATH=/usr/share/java/kafka-connect/plugins  
MONGO_PATH=${CONNECT_PLUGIN_PATH}/kafka-connect-mongodb-sink

./gradlew copyDependencies jar
sudo mkdir -p "${MONGO_PATH}"
sudo cp ./build/third-party/*.jar ./build/libs/*.jar "${MONGO_PATH}"
```

**Comment by blootsvoets** [comment]
Looking again at the README, it does seem to list these steps. Is the mongodb java driver in `build/third-party` after you run `./gradlew build`? Is it added to your plugin path?

**Comment by psmod2** [comment]
Hi,

Sorry - I may have approached this the wrong way - I simply download the JAR - `kafka-connect-mongodb-sink-0.2.1.jar` from your releases page: https://github.com/RADAR-base/MongoDb-Sink-Connector/releases

So what you're saying is I need to actually checkout the code then run the gradle task `copyDependencies` ?

Thanks

**Comment by blootsvoets** [comment]
For now, yes. It’s a good suggestion for improving our build, then we could include a zip with dependencies instead in the release. We’ll track this with #32.
